// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: storages/storage_service.proto

package storages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_storages_storage_service_proto protoreflect.FileDescriptor

const file_storages_storage_service_proto_rawDesc = "" +
	"\n" +
	"\x1estorages/storage_service.proto\x12\bstorages\x1a\x1estorages/storage_message.proto2\xcc\x01\n" +
	"\x0eStorageService\x12=\n" +
	"\x06Upload\x12\x17.storages.UploadRequest\x1a\x18.storages.UploadResponse(\x01\x12>\n" +
	"\aGetFile\x12\x18.storages.GetFileRequest\x1a\x19.storages.GetFileResponse\x12;\n" +
	"\x06Delete\x12\x17.storages.DeleteRequest\x1a\x18.storages.DeleteResponseB*Z(lms-storage-service/pb/storages;storagesb\x06proto3"

var file_storages_storage_service_proto_goTypes = []any{
	(*UploadRequest)(nil),   // 0: storages.UploadRequest
	(*GetFileRequest)(nil),  // 1: storages.GetFileRequest
	(*DeleteRequest)(nil),   // 2: storages.DeleteRequest
	(*UploadResponse)(nil),  // 3: storages.UploadResponse
	(*GetFileResponse)(nil), // 4: storages.GetFileResponse
	(*DeleteResponse)(nil),  // 5: storages.DeleteResponse
}
var file_storages_storage_service_proto_depIdxs = []int32{
	0, // 0: storages.StorageService.Upload:input_type -> storages.UploadRequest
	1, // 1: storages.StorageService.GetFile:input_type -> storages.GetFileRequest
	2, // 2: storages.StorageService.Delete:input_type -> storages.DeleteRequest
	3, // 3: storages.StorageService.Upload:output_type -> storages.UploadResponse
	4, // 4: storages.StorageService.GetFile:output_type -> storages.GetFileResponse
	5, // 5: storages.StorageService.Delete:output_type -> storages.DeleteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storages_storage_service_proto_init() }
func file_storages_storage_service_proto_init() {
	if File_storages_storage_service_proto != nil {
		return
	}
	file_storages_storage_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storages_storage_service_proto_rawDesc), len(file_storages_storage_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storages_storage_service_proto_goTypes,
		DependencyIndexes: file_storages_storage_service_proto_depIdxs,
	}.Build()
	File_storages_storage_service_proto = out.File
	file_storages_storage_service_proto_goTypes = nil
	file_storages_storage_service_proto_depIdxs = nil
}
